-- Production schema for the Crop Disease application.
-- The backend owns authorization and connects over SSL; browser roles receive no table access.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.app_schema_migrations (
    version integer PRIMARY KEY,
    applied_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.diseases (
    class_name text PRIMARY KEY,
    crop text,
    disease_name text,
    symptoms text NOT NULL,
    recommended_treatment text NOT NULL,
    severity_level text
);

CREATE TABLE public.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    email text NOT NULL,
    profile_picture text,
    auth_provider text NOT NULL,
    provider_account_id text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_login_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_provider_account_unique UNIQUE (auth_provider, provider_account_id)
);

CREATE UNIQUE INDEX users_email_lower_unique ON public.users (lower(email));

CREATE TABLE public.auth_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash text NOT NULL UNIQUE,
    csrf_token_hash text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone
);

CREATE TABLE public.oauth_states (
    state_hash text PRIMARY KEY,
    return_to text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL
);

CREATE TABLE public.scans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    timestamp timestamp with time zone NOT NULL DEFAULT now(),
    predicted_class text NOT NULL,
    confidence double precision NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    image_hash text NOT NULL,
    original_filename text,
    content_type text,
    file_size integer CHECK (file_size IS NULL OR file_size >= 0),
    model_name text,
    model_version text,
    detection_status text,
    quality_status text,
    quality_warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT scans_id_user_unique UNIQUE (id, user_id)
);

CREATE TABLE public.feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    scan_id bigint,
    timestamp timestamp with time zone NOT NULL DEFAULT now(),
    predicted_class text NOT NULL,
    confidence double precision CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    message text,
    CONSTRAINT feedback_owned_scan_fk
        FOREIGN KEY (scan_id, user_id) REFERENCES public.scans(id, user_id) ON DELETE CASCADE
);

CREATE INDEX auth_sessions_user_expires_idx
    ON public.auth_sessions (user_id, expires_at);
CREATE INDEX auth_sessions_active_token_idx
    ON public.auth_sessions (token_hash) WHERE revoked_at IS NULL;
CREATE INDEX oauth_states_expires_idx
    ON public.oauth_states (expires_at);
CREATE INDEX scans_user_timestamp_idx
    ON public.scans (user_id, timestamp DESC);
CREATE INDEX feedback_user_timestamp_idx
    ON public.feedback (user_id, timestamp DESC);

CREATE OR REPLACE FUNCTION public.set_users_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE FUNCTION public.set_users_updated_at();

INSERT INTO public.app_schema_migrations(version) VALUES (1)
ON CONFLICT (version) DO NOTHING;

ALTER TABLE public.app_schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.diseases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.oauth_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.app_schema_migrations FROM anon, authenticated;
REVOKE ALL ON TABLE public.diseases FROM anon, authenticated;
REVOKE ALL ON TABLE public.users FROM anon, authenticated;
REVOKE ALL ON TABLE public.auth_sessions FROM anon, authenticated;
REVOKE ALL ON TABLE public.oauth_states FROM anon, authenticated;
REVOKE ALL ON TABLE public.scans FROM anon, authenticated;
REVOKE ALL ON TABLE public.feedback FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.auth_sessions_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.scans_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.feedback_id_seq FROM anon, authenticated;
